# put your configuration values here

[runtime]
log_level="WARNING"  # the system log level of dlt
# use the dlthub_telemetry setting to enable/disable anonymous usage data reporting, see https://dlthub.com/docs/reference/telemetry
dlthub_telemetry = true
workspace_id = "24581a78-48db-4ede-a948-cf8ddd3667fa"

[destination.anthropic_destination]                                                                                               
destination_type = "motherduck" 